### ISSUE TITLE
Sigma status

### ISSUE THREAD

**Issue by sharpaper** [jacomyal/sigma.js#1030]
Sorry, only a general question: the last commit was 3 years ago so I was wondering if sigma is dormant or if it still developed/maintained? Thanks.

**Comment by Yomguithereal** [comment]
Hello @sharpaper, if you check the v2 version you'll see that there are still commits on the repo :). Basically the v2 does work but since I don't have time to document it, it's not made official yet. You can check the examples on the v2 branch if you want to explore nonetheless. You'll find it's more modern and uses the `graphology` library as its new graph model.

**Comment by JeffSpies** [comment]
I recently made decisions not to use sigma.js as opposed to, e.g., cytoscape.js, because of the issue @sharpaper raised. Had I known about V2, I would have at least tried it (and now I will). 

Would you be open to adding a statement to the README about the future of the project with respect to V2? Obviously, a roadmap, some general statement about the goals (e.g., I read in another issue I read about graphology and package-manager friendliness), and/or an expected release data would be ideal, but anything to say the project isn't dead would probably be useful. I've been searching for something like it and can't find it--apologies in advance if I've missed it. I can submit a PR saying what I know, but I suspect that it would be more accurate/efficient for it to come from you, @Yomguithereal, or @jacomyal.

Either way, excited for V2!

**Comment by Yomguithereal** [comment]
This would be a nice way to direct people to the v2 indeed (which is already in production in most of my labs' apps anyway, it's just that it's not documented nor very stable nor support as many feature as the current v1).

**Comment by JeffSpies** [comment]
Are your labs' apps online?

And if you'd like me to submit a PR with a general statement that you can add to, I'd be happy to do that.

**Comment by Yomguithereal** [comment]
Sure, they are all FOSS and you can find some here: http://tools.medialab.sciences-po.fr/

This one, for instance, uses sigma v2: http://hyphe.medialab.sciences-po.fr/ and has a public demo here: http://hyphe.medialab.sciences-po.fr/demo/#/login

This one also: http://tools.medialab.sciences-po.fr/graph-recipes/
