### ISSUE TITLE
CurvedArrow edges are only shown upon hovering in V1.2.1

### ISSUE THREAD

**Issue by mahmoudafer** [jacomyal/sigma.js#1052]
in sigma v1.2.1 when edges type is set to curvedArrows, a straight line is rendered between the nodes and the curved arrows are only visible when hovered over. When I downgraded to v1.1.0, it worked

**Comment by philippjess** [comment]
Thats working in my project.

**Comment by mahmoudafer** [comment]
> Thats working in my project.

Try this codepen: https://codepen.io/mahmoudafer/pen/ExxoLxb

**Comment by philippjess** [comment]
Pretty weird, it doesnt get more basic than this. And its working if you only switch the sigma.js to an older version?

**Comment by mahmoudafer** [comment]
Yes

> Pretty weird, it doesnt get more basic than this. And its working if you only switch the sigma.js to an older version?

**Comment by AVermeij** [comment]
I ran into this before as well - it's because ``sigma.canvas.edges.curvedArrow.js`` (here: https://github.com/jacomyal/sigma.js/blob/master/src/renderers/canvas/sigma.canvas.edges.curvedArrow.js) is not included in https://github.com/jacomyal/sigma.js/blob/master/Gruntfile.js.

Add it to the Gruntfile in your sigma dir, run ``npm run build`` and you'll get a ``sigma.min.js`` in the ``build`` folder which should work as expected.

**Comment by mahmoudafer** [comment]
> I ran into this before as well - it's because `sigma.canvas.edges.curvedArrow.js` (here: https://github.com/jacomyal/sigma.js/blob/master/src/renderers/canvas/sigma.canvas.edges.curvedArrow.js) is not included in https://github.com/jacomyal/sigma.js/blob/master/Gruntfile.js.
> 
> Add it to the Gruntfile in your sigma dir, run `npm run build` and you'll get a `sigma.min.js` in the `build` folder which should work as expected.

Ohh ok thanks i did not see that tho i looked for any missing imports, thanks again!
