### ISSUE TITLE
Sigma JS Example

### ISSUE THREAD

**Issue by hardypark** [jacomyal/sigma.js#1067]
I was wondering how to display a graph as done in sigmajs.org?

![image](https://user-images.githubusercontent.com/4219847/72566249-78645780-3881-11ea-8911-9170be0261bd.png)

**Comment by maxcorbeau** [comment]
You have an example here:
https://github.com/jacomyal/sigma.js/blob/master/examples/animate.html

Basically it's up to you to define the X, Y positions so that nodes are positioned in a grid format. There are libraries such as networkx that can help you generate graph files in grid format:
https://networkx.github.io/documentation/stable/auto_examples/drawing/plot_four_grids.html

And you can find some JavaScript code samples too:
https://stackoverflow.com/questions/25755120/how-to-generate-my-grid-coordinates-based-on-a-dynamic-grid-size-in-javascript

**Comment by hardypark** [comment]
Thank you for your input! The links you posted were helpful!
