### ISSUE TITLE
dense network with overlapping nodes

### ISSUE THREAD

**Issue by jzhoupu** [jacomyal/sigma.js#107]
Undesired behavior when nodes are very dense and overlapping on each other:
1. the example of "Accessing node attributes" code has trouble in displaying annotations correctly when nodes are overlapping - sometimes popups are not displayed when mouse moves between overlapping nodes. I guess this will be a general problem if 'overnodes' and 'outnodes' bindings are used.  I am new to programming so I am not sure how to fix this, probably changing the events and make sure only one node is active at a time  should do.
2. multiple node labels are displayed if mouse over overlapping nodes - this is or isn't a problem depending on expectations, probably displaying one at a time or at least providing this option should be good.

**Comment by emergingdzns** [comment]
Anyone ever get this going?

**Comment by Yomguithereal** [comment]
There could be a partial solution by changing [this](https://github.com/jacomyal/sigma.js/blob/master/plugins/sigma.layout.forceAtlas2/supervisor.js#L149) line to take the rendered size of the nodes rather than the absolute one (by using node properties prefixes). This won't work correctly however when zoomed since sizes won't be refreshed for sanity and performance reasons (it wouldn't work correctly in Gephi either by the way).

I might add some options related to this issue soon. The reason why it's not done by default is because it would break a lot of cases where multi cameras/renderers exist on a single graph.

**Comment by apitts** [comment]
Many thanks as always @Yomguithereal! I too would certainly appreciate an option for this.
