### ISSUE TITLE
The Typescript overhaul's aftermath

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1089]
Hello @jacomyal and @sim51. As foretold, here are the subjects remaining to be addressed after @sim51's #1085 TypeScript overhaul:

- [ ] what kind of linting do we want? For now I have sticked to @sim51's suggestions in the PR in the form of the following config (which identifies a lot of things to fix :) ):

```json
{
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "@typescript-eslint"
    ],
    "extends": [
      "plugin:@typescript-eslint/recommended"
    ],
    "rules": {
      "@typescript-eslint/camelcase": "off"
    }
}
```

- [ ] what kind of prettier config do we want? I have added a `npm run prettier` command for those not using an IDE tied to prettier. Is the config in `.prettierrc.json` ok?
- [ ] should we drop the glsl files and revert back to js strings shaders? I went this way to benefit from syntax highlight but I must admit it puts a lot of pressure and complexity on the transpilation/building mechanics.
- [ ] last but not least: how to we build/dist/release the files. I tweaked back the `npm run dist` command so we can safely go forward and publish the transpiled js sources as before but how do we publish the TS source, the ES6 one etc. and do we address the `index` issue? Should we be able to require sigma as a whole? as separate files or chunks etc.

**Comment by Yomguithereal** [comment]
Also can someone explain to me whether one needs to tell keys are optional in an object type in TypeScript? Cannot get an answer for that anywhere. It seemed to me it was an difference between the interface and the type but examples are yelling about the layout option objects...

**Comment by sim51** [comment]
For the linter, usually I take the default one.
We can take a look at all the "thing to fix" with the corresponding rules, and see if we disable or fix them.
What do you think about this strategy ?

About prettier, it's pretty much the same thing for me, I just need one, whatever the rules are, except for the line width. Usually it's 80 chars and for me it's too short (that's why I put 120).

For `glsl` files, I let you guys take a decision, I have no opinion on this topic.

For the `index` issue, I'm sure I can correct it with the TS config. I have created an issue for that ( #1090 )

For the build process, it's a good point, I need to make some search.

**Comment by Yomguithereal** [comment]
Just writing those urls for record later (as discussed with @jacomyal regarding glsl files):

- https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates
- https://www.jetbrains.com/help/webstorm/using-language-injections.html#ws_configure_injection_background

**Comment by sim51** [comment]
Since our last work on typescript, there is no more lint error (just a few warnings).
And the package has been review  in september by @jacomyal  with the export of types.
