### ISSUE TITLE
[v2] sigma.js + graphology + graphology-gexf umd version 

### ISSUE THREAD

**Issue by alx** [jacomyal/sigma.js#1108]
Hi @jacomyal,

The last few days, I've been trying to run sigma.js v2 version inside a Hugo project with something like this:

```html
<script src={{ "js/sigma.js" | absLangURL }}></script>
<script src={{ "js/graphology.umd.min.js" | absLangURL }}></script>
<script src={{ "js/graphology-gexf.umd.js" | absLangURL }}></script>
<script>

  var container = document.getElementById("graph-container");
  var x = new XMLHttpRequest();

  x.open("GET", {{ .Params.gexf | absLangURL }}, true);
  x.onreadystatechange = function () {

    if (x.readyState == 4 && x.status == 200) {

      var doc = x.responseXML;
      var graph = gexf.parse(graphology.Graph(), doc);
      var renderer = new Sigma.WebGLRenderer(graph, container);

    }
  };
  x.send(null);
</script>
```

I was able to build `graphology.umd.min.js` easily, but `graphology-gexf.umd.js` needed more work (just adding a `rollup.config.js` with correct parameters).

Is it "a" way to do it ? Or have I missed something in the building process that could reduce the workflow to generate umd graphology files ?

Thanks and have nice holidays,

Alex

**Comment by Yomguithereal** [comment]
Hello @alx, there is not a single way to do it but most people would now build a single bundled javascript file containing your code and its dependencies (that can be required through `require` or ES6 imports) by using `webpack`, `rollup` or `browserify` for instance. This massively reduce the generation workflow since you will only build one file in the end. You can also use this strategy to build several files such as one for all external libraries bundled together and your own code in another one.

But if you want to keep using `umd` packages, then using rollup to generate all the necessary files also works fine as you did.

**Comment by alx** [comment]
thanks @Yomguithereal for your answer, it's clearer now.
