### ISSUE TITLE
Merge canvas and export to png

### ISSUE THREAD

**Issue by wantnocode** [jacomyal/sigma.js#1150]
## Feature request template
want merge canvas and export to png / svg.

**Describe the solution you'd like**
want merge canvas and export to png / svg.

**Describe alternatives you've considered**
A new Canvas render all context, then downloadImage

**Comment by jacomyal** [comment]
Hi @wantnocode,

Sigma's rendering is raster based, so you won't be able to get a SVG export. If you want to draw a graphology graph as an SVG, you can still look at [graphology-svg](https://graphology.github.io/standard-library/svg.html).

About the PNG, it is possible, but not implemented yet. Since extracting the images is not done the same way for WebGL canvases and classic canvases, I agree it would be nice if sigma directly provided some helper for this.

Waiting for it to reach a production version, you probably already can extract it this way:
1. For each [sigma layer](https://github.com/jacomyal/sigma.js/blob/f52af9ed7842e8ca825cf54e1941032f7283eaaf/src/sigma.ts#L171-L177), extract the `"2d"` or `"webgl"` context (using `canvas.getContext(...)`)
2. Use [`#getImageData`](https://developer.mozilla.org/fr/docs/Web/API/CanvasRenderingContext2D/getImageData) for Canvas contexts and [`#readPixels`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels) for WebGL contexts (you then have to convert the result into a proper `ImageData`)
3. To blend all those `ImageData`s together, I think you can just use [`#putImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData) on a new canvas
4. With this final canvas, you can easily extract the final image, using [`#toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) for instance

I hope it helps!

**Comment by wantnocode** [comment]
Thank you. 
About the export to PNG,I'm doing it

**Comment by jacomyal** [comment]
Finally, we decided not to add it directly into the core lib, since there are multiple things to take into account (layers to display, capture with a given camera state or stage dimensions, etc...). So, instead of offering a limited helper, I'll add an exemple showing how it can be done. Also, I will come with two new public methods to retrieve a safe collection of settings and a safe collection of canvases.

We just need to test a bit more the example (on Retina displays particularly), but it should be released soon. It is already available in the `issue-1150` branch.
