### ISSUE TITLE
[v2] Leaflet map coordinates to SigmaJS v2 coordinates

### ISSUE THREAD

**Issue by gajicdev** [jacomyal/sigma.js#1155]
Hi

I am trying to draw a network onto a Leaflet map.

The "sigma-container" and the "map-container" are the same size and overlapping(sigma in foreground).

As a start, I wanted to draw one node on a specific position e.g. New York (Lat/Y: 40.7128, Long/X: -74.0060).

For that I use the Leaflet map's project method:
https://leafletjs.com/reference.html#map-project

E.g:

```typescript
const p = map?.project([40.7128, -74.0060])
x = p?.x;
y = p?.y;

const graph = new Graph();
graph.addNode("XR-3", {
                x: y,
                y: x,
                size: 15,
                label: "XR-3",
                type: "image",
                image: "router.png",
            });

const container = document.getElementById('sigma-container') as HTMLElement;
const renderer = new Sigma(graph, container, {
        nodeProgramClasses: {
            image: getNodeProgramImage(),
        },
        renderEdgeLabels: true,
    });
```

This draws the node however into the center of the Map:
![image](https://user-images.githubusercontent.com/47570664/141324689-dfb02548-c0e3-4b5e-9f53-4b80984a8d47.png)

So if I am not mistaken, the nodes are being drawn depending on other node's sigma-coordinates?
How can I ensure that by default the area is wider and draw a node to the x/y-coordinates of the sigma-container div?

Thanks

**Comment by sim51** [comment]
Please, consider to use stackoverflow to ask question on "How I can do ..." instead of creating an issue on the project.

To render a node at a specific position, you should use the method [sigma.viewportToGraph](https://github.com/jacomyal/sigma.js/blob/main/src/sigma.ts#L1440-L1451) to translate the screen position to the graph position.

Moreover, the method `project` in leaflet gives the relative position (in pixel) from the center of map, so the point (0,0).

I recommend you to use a nodeReducer for that : 
```
renderer.setSetting("nodeReducer", (node, data) => {
   // get the relative position (in pixel) of the coord from the CRS origin
  const mapViewportPosition = map.project([data.lat, data.long], map.getZoom());
  // get the CRS origin position on the screen
  const mapCenterViewportPosition = map.getPixelOrigin();
  // project the screen position in the graph
  const graphPosition = renderer.viewportToGraph({
    x: mapViewportPosition.x - mapCenterViewportPosition.x,
    y: mapViewportPosition.y - mapCenterViewportPosition.y
  });
  return {
    ...data,
    x: graphPosition.x,
    y: graphPosition.y,
    color: "#000",
    size: 10
  };
});
```

I started to create an example for that : https://codesandbox.io/s/sigma-with-leaflet-lepn9?file=/index.ts:937-1453
The example doesn't sync (yet?) the pan on the map/graph,, as well as the resize.

**Comment by gajicdev** [comment]
Thx, sorry for opening an issue. Will keep it in stackoverflow from now on! 👍

**Comment by sim51** [comment]
@gajicdev  I updated the codesandbox demo, the pan is there now, and the example is more clear.
There is still an issue on map borders, but it works well.

**Comment by gajicdev** [comment]
@sim51 Works fantastic thx! Any idea how to solve the problem when 2 nodes have the exact same position?

**Comment by jacomyal** [comment]
Maybe using [graphology-layout-noverlap](https://graphology.github.io/standard-library/layout-noverlap) could help?
