### ISSUE TITLE
minZoom & maxZoom options missing

### ISSUE THREAD

**Issue by leonard97** [jacomyal/sigma.js#1161]
## Problem
In Sigma JS v1 it was possible to add a `maxZoom` and `minZoom` value to the graph to limit the zoom level of it. Also the `autoRescale` option was present which administered the relative or absolute size of the nodes while zooming.

## Solution
It would be great if those options would be integrated into Sigma JS v2 so these rendering settings can be passed on graph creation.

**Comment by jacomyal** [comment]
Hi @leonard97,

The `minZoom` and `maxZoom` features are quite straight-forward to implement, and it seems clearly useful and not doable outside of sigma, so we will work on it soon I think.

For your other concern, about the `autoRescale` feature, it is a bit different to me: The feature was quite "magical", and I wouldn't just add it like it was, today. I see the need and I myself have this issue in some applications, but it required a better design I think.

I'll split those two features in separate tickets, since they will be dealt with differently. Thanks for the report!

**Comment by jacomyal** [comment]
The new ticket about the `autoRescale` option is #1162.
