### ISSUE TITLE
Simplify and optimize multiplyVec util

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1170]
https://github.com/jacomyal/sigma.js/blob/main/src/utils/matrices.ts#L76-L98

**Comment by Yomguithereal** [comment]
Why is the third component of the vector `0` here: [Math.cos(cameraState.angle), Math.sin(cameraState.angle), 0] ?

**Comment by Yomguithereal** [comment]
Note: maybe we could keep specialized matrices to speed up conversions from the different spaces, like it's done [here](https://github.com/graphology/graphology/blob/master/src/layout/utils.js#L104-L125).

**Comment by jacomyal** [comment]
> Note: maybe we could keep specialized matrices to speed up conversions from the different spaces, like it's done [here](https://github.com/graphology/graphology/blob/master/src/layout/utils.js#L104-L125).

Hum, I don't see how the code you point is different from the one in sigma (but maybe the links are outdated and the code have been updated since).

**Comment by jacomyal** [comment]
> Why is the third component of the vector `0` here: https://github.com/jacomyal/sigma.js/blob/main/src/utils/index.ts#L362 ?

Here, I only want to compare the size of a transformed vector to the width of the viewport. Giving `0` or `1` is the same, since the 1 (and the 3rd dimension, actually) is only here to handle affine transformations (ie. translations, that do not change the size of the vector).

So, I agree, this multiplyVec could be simplified, by always adding the 1 for the first dimension to the input, and always returning only `[x, y]`. I see how it could simplify the code (which is very good), but I don't see how it would optimize it.
