### ISSUE TITLE
Node size significantly differs based on graph size

### ISSUE THREAD

**Issue by RuthgerD** [jacomyal/sigma.js#1185]
Node size significantly differs based on graph width which is really unexpected.

I've done some research and this could be related to the thing called "correctionRatio" since thats the only thing affecting the final size other than size + camera zoom in the node vertex shader.

This might be feature to some but for my use case this is a total bug.

### Versions

**Sigma.js version:** ^2.1.2
**Graphology version:** ^0.23.1
**Operating System:** Arch Linux & Windows 11
**Web browser:** Google Chrome 96

### Steps to reproduce

1. add a couple of nodes spread over the x axis

Normal zoom level:
![image](https://user-images.githubusercontent.com/57626200/144714881-940e1b0b-efaf-41aa-9eba-9358036cda14.png)
Fully zoomed out (with edges hidden):
![image](https://user-images.githubusercontent.com/57626200/144714906-dc113ca1-ead4-421d-a6fe-bee93cc4e030.png)

2. add 1000+ nodes spread over the x axis

Normal zoom level:
![image](https://user-images.githubusercontent.com/57626200/144714853-6383e751-7f7b-45da-8c40-d79516c3e166.png)

Fully zoomed out (with edges hidden):
![image](https://user-images.githubusercontent.com/57626200/144714920-e2fe81cc-0f4a-4f4b-84af-6ad02569d870.png)

observe the difference of the node size at the same zoom level

### Expected behavior

Node size should remain constant for the same zoom level regardless of graph size

### Actual behavior

Node size depends on the graph size

**Comment by jacomyal** [comment]
Hi @RuthgerD,

Here is how it works in sigma currently:
1. The positions of the nodes are automatically rescaled, so that the graph fits "by default" in the stage
2. The sizes of the nodes are preserved, so that a node with a size of 30 is displayed with a radius of 30 pixels with the default camera (or any camera with a `state.ratio` of 1) (edges thicknesses work in a similar way)
3. When the user zooms in the graph, the nodes are displayed with a radius of `node.size / Math.sqrt(camera.state.ratio)`, so that nodes don't grow too big when zoomed in, nor too small from afar

I stand with these design choices for most cases I personally meet. Indeed, when using force-directed layouts, for instance, the important result is the relative positions of nodes relatively to the other ones, and not their exact coordinates. While having a clear and easy way to determine what size a node will have on screen felt more important.

However you are not the first to report this problem (see #1161 and #1162), and I myself had a usecase recently where I would have wanted a different way to scale node sizes, so that it fits their positions.

Here are solutions I can imagine:
1. Adding a way to disable/enable this `Math.sqrt(camera.state.ratio)` ratio rule
2. Adding a way to require sigma to rescale node sizes using the same ratio than it does with the node positions

@Yomguithereal What do you think about this?

(btw I'll close the ticket #1162 as this one here is now more documented.)

**Comment by paulkre** [comment]
Any news on this? I really think the "auto scale" feature should not be enabled by default. At the very least there should be a parameter to disable it.

**Comment by jacomyal** [comment]
It is now possible, in v3+, with the `itemSizesReference` and `zoomToSizeRatioFunction` settings (example [here](https://github.com/jacomyal/sigma.js/blob/e1bf70052caa31c6820f0aa274517f6947edc106/packages/examples/fit-sizes-to-positions/index.ts#L24-L25)).

I'm cleaning the issues that are solved in the `v3` branch, to get more visibility on what's left to do.
