### ISSUE TITLE
Edge labels will be hidden when node labels are empty/null

### ISSUE THREAD

**Issue by Kimi-Gao** [jacomyal/sigma.js#1200]
**Sigma.js version:** 2.1.3
**Graphology version:** 0.23.2
**Operating System:** macOS 11.6
**Web browser:** Version 97.0.4692.71 (Official Build) (x86_64)

### Steps to reproduce

1. set `renderEdgeLabels: true` when `new Sigma`
2. set `label` to `''` in `nodeReducer`
3. set `label` to `'222'` or other string in `edgeReducer`

Check the live example https://codesandbox.io/s/pensive-jepsen-fnr05?file=/index.ts

### Expected behavior

Edge labels should be displayed

### Actual behavior

- Edge labels are hidden which seem very odd.

![image](https://user-images.githubusercontent.com/12554487/149085733-40717819-2a45-4c02-9827-fbda95616cc8.png)

- Edge labels will be displayed when hovering nodes

![image](https://user-images.githubusercontent.com/12554487/149085795-2b311e84-6ac8-4954-bfed-e6d12d3afef7.png)

## Note

If the issue has an inactivity of **30 days**, it becomes stale.
With an additional inactivity of **14 days**, the issue is closed

**Comment by jacomyal** [comment]
Hi @Kimi-Gao,

Thanks for this report!
This indeed is an issue, and a fix will be released with v2.2.0.

---

Since there are a few undocumented decision that have been made on labels rendering related topics, here are a few things I prefer to write here, mostly for future me who will fix this when I have time:

1. We chose to only display edge labels by default when both extremities have their labels visible:
https://github.com/jacomyal/sigma.js/blob/c0a55d5517726f4081682564ee7b98035e8ae312/src/core/labels.ts#L140-L142

2. We can force an edge label to be displayed, using `res.forceLabel = true;` (this is implemented and pushed to `main`, but not released yet, so not available in v2.1.3):
https://github.com/jacomyal/sigma.js/blob/39833bc304ecb41e34c7a173a891da36850e38a3/src/sigma.ts#L758

3. Nodes with a `null` label are considered as with no label, while nodes with empty `""` label should be considered as with a label. This explains the empty highlighted rectangle, while a node with a `null` label will have none:
![image](https://user-images.githubusercontent.com/144846/149118025-e6496fe7-d1f0-4299-80e4-087f08798f63.png)
![image](https://user-images.githubusercontent.com/144846/149118089-6695c730-f1a3-4887-bee8-a2f72f2b0a50.png)

Considering this, indeed, with empty node labels, (most) edge labels should be visible in your example. The issue comes from here:
https://github.com/jacomyal/sigma.js/blob/39833bc304ecb41e34c7a173a891da36850e38a3/src/sigma.ts#L722-L723
Here, the condition should be `if (typeof data.label === "string")` instead.

**Comment by avenzi** [comment]
Just a heads up - in PR #1199, I change that exact condition on line 722 to
`if (data.label && !data.hidden)` to also account for hidden nodes.

**Comment by Kimi-Gao** [comment]
Hi @jacomyal , thanks for your detailed answer. Looking forward to the next release.

**Comment by jacomyal** [comment]
I just pushed a fix (and merged @avenzi's PRs as well), so it now works properly on the `main` branch. It will be shipped with the upcoming v2.2 version.
