### ISSUE TITLE
Retrieve nodes that are within viewport bounds (visible nodes)

### ISSUE THREAD

**Issue by tom-osint** [jacomyal/sigma.js#1212]
It'd be incredibly useful to have a clean way of retrieving nodes that are in viewport bounds.
I'm rendering font-awesome icons in the DOM using a view to screenspace transform, however for 20k nodes this starts to cause serious performance issues.

My idea is to dynamically display icons by culling nodes that are out of viewport bounds.

My initial thoughts were that I could filter the nodes based on coordinates, but this would get slow with more nodes.
I was wondering if we could use quadtrees instead to boost performance.

Something like `renderer.visibleNodes()` or `renderer.forEachVisibleNode((n, a) => { /* do something cool */ })`

Cheers.

**Comment by Yomguithereal** [comment]
@tom-osint a sigma renderer already has its own quadtree used to query nodes under your mouse and to avoid rendering canvas items that are not displayed on screen such as labels. You should be able to use it for your own goals by accessing `this.quadtree` (TS might not let you do so, but there is nothing a cast cannot solve). See an example of this here: https://github.com/jacomyal/sigma.js/blob/main/src/sigma.ts#L942-L950

This is not as integrated as what you propose but it should be working, we shall think about `forEachVisibleNode` in an upcoming version maybe.

Note that our quadtree is voluntarily including nodes that might be outside the viewport because to avoid label flickering in some cases so be sure to perform a filter on the subset of nodes returned by the quadtree to ensure they really are visible (including some geometry about the node shape because it usually is more than a point).

**Comment by jacomyal** [comment]
The new package [@sigma/utils](https://www.npmjs.com/package/@sigma/utils) exposes a `getNodesInViewport(renderer: Sigma): string[]` function, that returns the list of nodes visible in the current viewport. It is showcased here:
https://www.sigmajs.org/storybook/?path=/story/utils--get-nodes-in-viewport
