### ISSUE TITLE
Some demos don't work on  CodeSandBox

### ISSUE THREAD

**Issue by ibes** [jacomyal/sigma.js#1216]
Could you please check these demos. They show a error about the bundled js file

Unfortunately I don't know how to fix this and the demos are very very helful. 

https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/events
https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/mouse-manipulations

**Comment by kmalski** [comment]
Hi, I have encountered the same "bug" but it's more like codesandbox issue and in my case I just had to disable adblock 😃 Try it

**Comment by ibes** [comment]
No, was not enough for me. 
Firefox and Chrome tested. 
Both in plugin-less privacy tabs.
Used the events demo for the tests.

**Comment by kmalski** [comment]
Oh I found the difference. The examples you linked do not have `sandbox.config.json` file. If you want to play around with those examples, you should add that missing file with this content:
```json
{
  "infiniteLoopProtection": true,
  "hardReloadOnChange": false,
  "view": "browser",
  "template": "create-react-app"
}
```
And then you have to refresh the page (this was important for me, because codesandbox did not reload project without this).

Despite this temporary fix, I think these examples should be fixed and proper configuration files should be added.

**Comment by ibes** [comment]
That did it for me!
Thanks!

**Comment by sim51** [comment]
Codesandbox config file has been added in every example.
