### ISSUE TITLE
Curved edges

### ISSUE THREAD

**Issue by andyle13** [jacomyal/sigma.js#1231]
Hello, currently I'm using [@react-sigma](https://github.com/sim51/react-sigma) with the attempt to render parallel edges. I have managed to do that using [graphology](https://github.com/sim51/react-sigma/issues/24) which seems to work flawlessly. Although, [curved edges](https://dunnock.github.io/react-sigma/?path=/story/plugins--edge-labels) would be a nice-to-have for presentation's sake such that the labels aren't overlapping. It appears that you used to have that feature in v1. Do you have any plans on reviving it in v2?

**Comment by sim51** [comment]
There is already a ticket about parallel edges #1197

**Comment by jacomyal** [comment]
Hello @andyle13,

If your question is about rendering parallel edges, then it is a very legit question, but that is already actively discussed in ticket #1197, as @sim51 said.

Else, if you specifically want to render curves edges, you can develop your own custom renderers. It is not properly documented yet (as for most of v2's code...), but you can check the [`custom-rendering` example](https://github.com/jacomyal/sigma.js/tree/main/examples/custom-rendering). Also, there is no curved edge program in sigma v2 yet, because:
- Edge events consider edges as thick straight lines (so it mostly works for arrows as well)
- Rendering curves in WebGL is very expansive (like several times more expansive than rendering lines)
