### ISSUE TITLE
Panning and zooming in Safari on 4k displays stutters

### ISSUE THREAD

**Issue by Nordalf** [jacomyal/sigma.js#1241]
## Panning and zooming in Safari on 4k displays stutters

To help us understand your issue, please specify important details, primarily:

- Sigma.js version : 2.2.0
- Graphology version : 0.24.1
- Operating system: MacOS (Monterey 12.3.1)
- Web browser: Safari 15.4
  
### Expected behavior
Able to use Sigma without stuttering / lagging in Safari in expanded browser mode

### Actual behavior
When connected to a 4k display in Safari and having the browser filling up the whole screen, the Sigma layout starts to stutter when panning the camera, zooming, and selecting nodes. When shrinking the window size, the issues are resolved. Also tested in Chrome (101.0.4951.64 (Official Build) (arm64)) where it works fine (though a small stutter in the beginning of initialisation).

**Comment by jacomyal** [comment]
I'll close this ticket, since it is old and related to sigma v2.

Quick comment, though, for people ending on this ticket anyway:
Sigma renders graphs on a canvas, using WebGL. The more pixels there are on the canvas, the more decisions on which color should the pixels be the WebGL has to take. So it is normal to get lower performances on larger canvases (in terms of pixels).
