### ISSUE TITLE
node.image distorts images when you have many of them

### ISSUE THREAD

**Issue by soler98012** [jacomyal/sigma.js#1257]
I'm drawing a graph with 39 png images on it, when rendering, they display properly at first but then glitch out and begin showing distorted or show the wrong image

sigma version: 2.3.1

**Comment by kaij** [comment]
This is something that is fixed when using the node.combined program in pull request at https://github.com/jacomyal/sigma.js/pull/1206. Unfortunately, the pull request was closed unmerged by the bot.

**Comment by boogheta** [comment]
Hello @kaij,

I met the same issue trying to display images on many nodes, so I tried to work with the code from your PR, but I wasn't actually  interested in the borders/zooming aspects of it and it was messing with the regular labels display, where I only wanted to fix the many images glitch on the regular node.image program.

So I allowed myself to retake only the pieces of your code doing that and applied it to the node.image code in the following commit and it works great in my case with close to a thousand pictures nodes: https://github.com/boogheta/sigma.js/commit/42ca940efeed77dcb144d1a19e539a5ae19b61ef

Although, since it is entirely your code, I feel a little bad requesting a PR for it, hence taking over your credits for it and only mentioning you in the commit's description.

I feel like it would make more sense if you would repropose yourself a PR with an identical commit doing just that, and I feel like this one would be accepted more easily since it actually fixes an issue without changing anything in the current labels/zoom behavior contrarily to the node.combined one.

What do you think?

**Comment by kaij** [comment]
@boogheta Thanks for coming up with this suggestion. I would be happy to provide a PR from the original code - but I feel like this would be lost work. 3 out of my 4 pull requests were closed by the bot (e.g. https://github.com/jacomyal/sigma.js/pull/1242).

**Comment by boogheta** [comment]
Yes but I guess that's because they were doing too many different things at once, this one will only fix the images loading issue which I think would be more easily reviewed and accepted.
FYI, I repushed my commit using the Co-author funtion of github so that you are credited as well on the commit.
So if that's simplier to you like this I can also propose a PR with this coauthored commit now.

**Comment by kaij** [comment]
@boogheta It's fine for me if you do the new PR (with the co-author mention), thanks

**Comment by sim51** [comment]
Sorry for the stalebot, I configured it so it will not touch PRs in the future.
