### ISSUE TITLE
Change node labels default alignment

### ISSUE THREAD

**Issue by vincent0965** [jacomyal/sigma.js#1261]
Modification of the node default position in the settings has no effect

Sigma.js version: 2.3.0
Graphology version: 0.24.1
vue version: 2.6.14

My problem is that when I want to set label for nodes is on the bottom hand side or node inside, and I used to json file save nodes info.

I set `defaultLabelAlignment:"bottom"` and look at the code,but both its unavail, anything I am doing wrong?
https://github.com/jacomyal/sigma.js/pull/468/files

Is it possible to move the label to others position of the node?

**Comment by jacomyal** [comment]
I decided to take the same decision as for #1357:

After having been thinking a lot on this issue, I decided to not implement it. Right now, sigma's APIs is made so that people who have advanced usecases should write their own label renderers. That's what we do [in the demo](https://github.com/jacomyal/sigma.js/blob/753a22c7c430c319746ef847240f9807ce3f80a3/packages/demo/src/canvas-utils.ts#L1-L0) for instance.

Also, labels rendering APIs might change in the near future (to handle #1319 for instance), so I don't want to commit more code/debt into it.
