### ISSUE TITLE
question about importing data

### ISSUE THREAD

**Issue by Arnold1** [jacomyal/sigma.js#1301]
Hi,

I would like to draw a decision tree with sigma.js - is that possible? the decision tree is available in graphviz / dot format. how can I import that data to sigma.js?

Thanks

**Comment by Yomguithereal** [comment]
Hello @Arnold1,

> I would like to draw a decision tree with sigma.js - is that possible?

sigma.js can very well draw a decision tree since trees are a special case of graphs. This said, sigma.js has been designed to render large graphs to perform visual network analysis and might not be suited to what you want to achieve. d3 might be a better fit here, for instance. What's more, `graphology` does not implement (yet) deterministic tree layout algorithms, as you can find in d3.

> the decision tree is available in graphviz / dot format. how can I import that data to sigma.js?

You would need a dot file parser such as [https://www.npmjs.com/package/@ts-graphviz/parser](https://www.npmjs.com/package/@ts-graphviz/parser). Then you would need to create a `graphology` graph from the parsed data as `graphology` has not dot parser as of yet.

**Comment by Arnold1** [comment]
here is what I did with d3: https://jsfiddle.net/k6zupbhx/1/ when I have 25k nodes - everything is very slow...
that's why I would like to plot this tree with sigma.js - would that work with webgl and sigma.js?

**Comment by Yomguithereal** [comment]
> here is what I did with d3: https://jsfiddle.net/k6zupbhx/1/ when I have 25k nodes - everything is very slow...
that's why I would like to plot this tree with sigma.js

Seems like a good idea to try with sigma.js then you are right.

> why is it not possible to use sigma.js and webgl for that?

It is possible. It's just that the community using sigma and graphology is very rarely working with trees so it had very few incentives to develop tree-related algorithms, that's all. 

> is someone else working on the graphology?

I am working on `graphology`. I could develop tree-based deterministic layout, even a graphviz parser but I don't have much time to dedicate to this since this is stuff nor me nor the people I work with have a need for right now. Could you elaborate a bit more on why you are using dot format (which is not suited to large amounts of data, usually) and what kind of tree layout you would require?

> do you know any other library which I could use in the meantime?

In your shoes, I would use something like [`@ts-graphviz/parser`](https://www.npmjs.com/package/@ts-graphviz/parser) to parse the data, then find a deterministic tree layout in d3, then build a `graphology` graph with the result and finally feed it to a sigma renderer.

**Comment by Arnold1** [comment]
I have a decision tree classier to train data. it generates me this huge tree with 25k nodes. similar to this library: https://mljar.com/blog/visualize-decision-tree/

I would like to plot it like that way with sigma.js instead d3:
https://mljar.com/blog/visualize-decision-tree/output_15_0.svg

**Comment by Yomguithereal** [comment]
> I would like to plot it like that way with sigma.js instead d3:

Once again sorry to rain on the parade but sigma.js was not design to render nodes as something else than basic shapes. This is because rendering is done in WebGL and can scale up very high but is not suited to render things such as text and boxes containing text with a specific layout etc. HTML and SVG are better at this but as you saw, they do not scale to 25k elements. So if you really need to obtain this kind of visual result: https://mljar.com/blog/visualize-decision-tree/output_15_0.svg sigma.js is not the good tool, and neither are d3 or anything else and the only solutions I can think of are virtualized dom lists, which is not trivial to use nor implement, or rasterized image representations. But if you can accept to render your nodes as circle and have some level of interaction on click/hover etc. to reveal the information of the nodes, then why not.

> all I found is the following - would that help?
> https://github.com/d3/d3-hierarchy
> https://observablehq.com/@d3/tree

Yes, I was thinking to this kind of things.

**Comment by Arnold1** [comment]
what about pixi.js rendering? similar to: https://embed.plnkr.co/plunk/N2VhEr

**Comment by Yomguithereal** [comment]
> I just need something which renders a tree structure with webgl and not canvas or svg...

A tree structure is just too vague. Your [example](https://mljar.com/blog/visualize-decision-tree/output_15_0.svg) show the structure as boxes containing text and arrows between the boxes. For this using WebGL is a nightmare and no webgl renderer in the world will actually do it. So it really boils down to how you actually want to display the tree and what compromises you are willing to make. Pixi.js will not do what you want (or what I understand that you want) either. If you really need boxes of text, I would rasterize the whole tree as a single image using canvas and then explore the image and zoom into it or something and this is not straightforward to do.

**Comment by Arnold1** [comment]
you would create a png of the entire tree and than use leafletjs to do the zooming?

**Comment by Yomguithereal** [comment]
Yup, if what you need is exactly [this](https://mljar.com/blog/visualize-decision-tree/output_15_0.svg) but with 25k boxes.

**Comment by Arnold1** [comment]
but that's svg - doesn't matter?

**Comment by Yomguithereal** [comment]
> but that's svg

I know but svg is one way to render this kind of stuff. Another one is to use a rasterizer (2d canvas IS a rasterizer) to paint a similar thing (but of course you will lose the benefits of having a vectorial data system that svg provides, but you can't have both peroformance and ease of use, it just does not exist).

> so that needs to be converted to png than?

you need to create the png yourself, using a drawing API (canvas 2d is one of them).

> I think leafletjs you would usemultiple tiles to get a good resolution?
something like that - but just apply the same to png?

it could be used to navigate a very large image yes.
