### ISSUE TITLE
leave* events when quitting the container

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1327]

**Comment by jacomyal** [comment]
@Yomguithereal could you detail this issue a bit more please?

**Comment by jacomyal** [comment]
OK, after unrecorded discussion, the issue is the following bug (that's been here forever, I agree):

#### How to reproduce

- Open a sigma graph
- Drag the stage so that a node touches the stage limits
- Move the mouse over the node
- Move the mouse outside the stage without leaving the node

#### Expected behavior

The node should become "unhovered".

#### Current behavior

The node remains "hovered".
