### ISSUE TITLE
Customize sandbox has a bug.

### ISSUE THREAD

**Issue by hussainmandavya** [jacomyal/sigma.js#1355]
I am trying to learn Sigma however the customize sandbox itself does not open.
Link to refer: https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/custom-rendering
I am using the latest version of sigma and I am really now to it.
I need to change the background color of the label then aa node is hovered. Kindly help
![image](https://user-images.githubusercontent.com/69156262/233960227-2dd5be0d-afd4-43bf-8409-cc049ccf8b47.png)

**Comment by overflowerror** [comment]
Seems to be an issue with the 3.0.0 alpha. As a workaround try changing the version to 2.4.0.

**Comment by sim51** [comment]
Yes it's an issue with the v3 alpha, and the examples have not been migrated to this version yet.

**Comment by hussainmandavya** [comment]
Thanks a ton guys.
I am trying to put borders on nodes using this customize sandbox and it somewhat works.
I am able to get borders at the loss of node color itself.
Kindly can anyone help me how to set borders on nodes while retailing the color of the node.
Thanks in advance

**Comment by sim51** [comment]
Hi,

Here is an example : https://codesandbox.io/s/kind-goldberg-zyuygl?file=/index.ts
You can combine two  programs to create one. So here I use the node  Image and node Border ones. 

By doing it, I saw an issue with the typescript definition of the program with the `NodeDisplayData` type, we can't extend it ... but data are there. So I used an any (which is bad !)

Instead of combining two programs, I recommend you to build your own

**Comment by hussainmandavya** [comment]
Really appreciate the help man. You're a life saver.
Thanks a ton.

**Comment by sim51** [comment]
You're welcome !
Can we close the ticket ?
