### ISSUE TITLE
Approx. Release of v3

### ISSUE THREAD

**Issue by Gykonik** [jacomyal/sigma.js#1356]
First of all, thank you for your great work on this library! I am just starting a new project where I need a library that supports the layouting and rendering of networks with ~5k nodes and ~50k links. I'm currently looking into possible libraries, and I really like sigma.js. I saw that you recently released v3.0 alpha. So I would like to ask if you have an approximate date when you will release the final v3 version, so I can include the latest version in my considerations. Thanks a lot! :)

**Comment by wthrajat** [comment]
following the issue...

**Comment by Gykonik** [comment]
Yeah, I'm also inquisitive. It would be such a pity to set up everything in the current v2.4 (or similar), and then v3 is released with breaking changes... :D

**Comment by jacomyal** [comment]
The main reason we started working on a v3 is because we found some issues with the main renderers that required some breaking changes to be fixed. Then, we thought about what we should break at the same time, taking this new version as an opportunity.

We are starting to get a more precise roadmap ([here](https://github.com/jacomyal/sigma.js/milestone/9), and not yet complete), and I hope we can release a proper v3 in 2023.

**Comment by jacomyal** [comment]
@Gykonik for the moment, custom renderers are the only thing impacted. Moving to v3 will take a bit of work - however, it will be way easier to develop custom renderers as well.

You can compare:
- [The main node program in v2](https://github.com/jacomyal/sigma.js/blob/v2.4.0/src/rendering/webgl/programs/node.ts)
- [The main node program in v3](https://github.com/jacomyal/sigma.js/blob/v3/src/rendering/webgl/programs/node.circle.ts)
