### ISSUE TITLE
Expose label background color and hover color in settings

### ISSUE THREAD

**Issue by Bytenex** [jacomyal/sigma.js#1357]
Hey,

currently it's not possible to color the label color when hovered or the background which makes it very hard to use on dark background. Currently I have set the font color to grey so it's visible on the dark background and the white hover background. As `labelColor` is already an object it would be suitable to add these settings to.

`
labelColor: {
    color: '#fff',
    hover: '#000',
    background: '#fff'
}
`

**Comment by Yomguithereal** [comment]
@Bytenex this can be dealt with using a custom label renderer such as this one here: https://github.com/medialab/ipysigma/blob/master/src/custom-label.ts (or if you want to customize the hover part: https://github.com/medialab/ipysigma/blob/master/src/custom-hover.ts)You can easily make your own to add support for a background color. Then you can pass those functions to your sigma instances in the settings as `labelRenderer` & `hoverRenderer`.

**Comment by jacomyal** [comment]
After having been thinking a lot on this issue, I decided to not implement it. Right now, sigma's APIs is made so that people who have advanced usecases should write their own label renderers. That's what we do [in the demo](https://github.com/jacomyal/sigma.js/blob/753a22c7c430c319746ef847240f9807ce3f80a3/packages/demo/src/canvas-utils.ts#L1-L0) for instance.

Also, labels rendering APIs might change in the near future (to handle #1319 for instance), so I don't want to commit more code/debt into it.
