### ISSUE TITLE
Sigma.js packaging

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1379]
# Description

- On npm we have the name `sigma` and also the organization `@sigma`.
- We also want to publish some special programs (or plugins like) on npm outside of the main library, like the image program
- the lib `sigma` should stay the standard way to use sigma (a kind of plug'n'play for standard scenarii ) 

So we need to define a good way of how to publish the project on npm,.

# One idea

Explode the code in multiple projects, to have a core project plus some others, like for example for programs. 
Example: 
- `@sigma/core`
- `@sigma/default-programs` 
- `@sigma/node-image-program` 
-  ... 

The sigma lib  will be just be a package.json with deps to `@sigma/core` + `@sigma/default-programs`.

What do you think @jacomyal @Yomguithereal ? 

- Does the idea to change the packaging seems legit to you ?
- Do you have an other architecture in mind ?

NB: Perhaps we need to firstly defined what can be an extra package for sigma.

**Comment by jacomyal** [comment]
Here are some thoughts:
- I don't like having to push a sigma version to fix a node-image-program bug
- I would like more features to be hosted on this repository, such as curved edges for instance
- I wouldn't want these new features to be packaged with sigma

So, I'm sure it would be better to split like you say. I agree with having a `sigma` package that is more plug-and-play (though I think I would like to move node-image-program outside of it). For the rest, `@sigma/core` makes sense to me, `@sigma/node-image-program` as well (and hopefully `@sigma/edge-curved-program` sometime). For `@sigma/default-programs` I don't know I prefer this or `@sigma/node-circle-program`, `@sigma/edge-arrow-program`, etc...

Another aspect to consider is how we want the repository to be organized. The current `src` files structure is kinda weird (having programs altogether in a folder, then all shaders in another one, rather than having one directory per program).

**Comment by Yomguithereal** [comment]
My points, in "vrac" (I did not re-read the whole discussion so they might be moot or redundant):

* We should keep a monorepo structure for stuff that need to benefit from functional testing, so we don't duplicate the complicated stack it requires. I don't know what's the go-to utility to deal with monorepo easily these days. I tend to somewhat use `lerna` but I think it is not maintained anymore.
* The `sigma` package should remain the main installation target, for convenience and backwards-compat (v3 is mostly aligned with v2 if you don't develop custom rendering anyway). It can be a compilation of other subpackages indeed. I don't really see the value in "over" splitting the core of the library into a core, renderers, camera etc. since we don't envision supporting something else than an interactive webgl renderer.
* I agree that the `@sigma` scope vs. `sigma-` prefixed packages means we can control the scope against potential squatting (the expression is a bit harsh lol)

**Comment by jacomyal** [comment]
OK, so here is a plan:
- [ ] Split codebase into a multi-packages repository (something similar to what @sim51 did in [react-sigma](https://github.com/sim51/react-sigma/tree/main/project/packages), with `sigma`, `examples`, `demo` and `website`
- [ ] Move `edge.triangle` into the `custom-rendering` example (I'm sure nobody uses it, partly because without anti-aliasing it makes things awful to read)
- [ ] Move `node.image` as a new `node-image-renderer` package (still in the same repo)
- [ ] Update documentation about how to release etc..

Then, the packages we would have would be:
- `sigma` (same as today, but without `edge.triangle` and `node.image`
- `@sigma/node-image-renderer`, with the current version of the factory (then we should add proper testing, and port some of [@Yomguithereal's take](https://github.com/Yomguithereal/sigma-experiments/blob/master/renderers/src/node/node.pictogram.ts) on it)

And for later, we could add `@sigma/edge-curve-renderer` and `@sigma/image-export` for instance.

**Comment by sim51** [comment]
What I purpose is the following structure : 

 - website.
 - project/
  |_ sigma/
      |_ package.json
  |_ demo/
      |_ package.json
  |_ examples/
      |_ package.json
  |_ custom-rendering/
  |_ node-image-renderer/
  |_ package.json

**Comment by sim51** [comment]
- [ ] Redo label renderer on demo 
- [ ] Review README
- [ ] Review examples with custom program
- [ ] Review examples with node hover/label render

**Comment by jacomyal** [comment]
I close this ticket since it's mostly done, and the remaining tasks haven't been discussed here yet.
