### ISSUE TITLE
Complex graph rendering

### ISSUE THREAD

**Issue by buger** [jacomyal/sigma.js#1385]
I have 2k entities and edges in my graph, and it starts getting messy. I wonder what are the good practicies to deal with it?
At the moment i'm filtering based on node degree, which makes it look nicer, but it also loose the data.

Can you give some example, on how to dynamically change Node degree filter, based on zoom level or similar?
Or maybe there are some other techniques out of there?

**Comment by jacomyal** [comment]
This is not the place to discuss these kind of topics, since we try to focus here on bugs and features request for sigma.js, so I'll close this ticket.

However, some quick notes: We (at [OuestWare](https://www.ouestware.com/)) use various strategies to tackle this problem:
- You can have a network with a layout, and play on filtering, search and/or highlighting, as we do in [Retina](https://ouestware.gitlab.io/retina/) ([example](https://ouestware.gitlab.io/retina/beta/#/graph/?url=https%3A%2F%2Fouestware.gitlab.io%2Fretina%2Fbeta%2Fdataset.gexf&c=c&s=s&sa%5B%5D=s&sa%5B%5D=r&ca%5B%5D=t&ca%5B%5D=c&st%5B%5D=t&st%5B%5D=c&ds=1&dc=1))
- You can dynamically build your graph, apply dynamic layouts, and allow your users to progressively expand the graph themselves, so they don't just get slapped with a huge graph at once. We have nothing public to showcase, but you can play with [Neo4J Bloom](https://neo4j.com/product/bloom/) to get some running example.
- You can offer more controls to your users on what they can do with their networks, as we do in [Gephi Lite](https://gephi.org/gephi-lite/) (completely inspired from [Gephi](https://gephi.org/)).

I hope this helps.
