### ISSUE TITLE
Node scaling issue on MacOS with NodeBorderProgram and NodePointProgram

### ISSUE THREAD

**Issue by gdotv** [jacomyal/sigma.js#1409]
- Sigma.js version : 3.0.0-beta12
- Graphology version : latest
- Operating system:  macOS (Apple Silicon)
- Web browser: Chromium

Issue encountered:
Node size scales should scale adequately as viewport is zoomed in (or out)
Actual behavior:
The node doesn't scale (though the hover label does) and looks smaller and smaller as the user zooms in.

See screenshot below highlighting the issue: 
<img width="971" alt="image" src="https://github.com/jacomyal/sigma.js/assets/95418630/7126f0ba-17db-4e25-94bf-63a4bf87a6d8">

I've attempted reproducing this issue on a Windows device and found that it doesn't occur. One interesting observation I've made in my investigation is that Node programs that use the sizing calculation method relying on u_correctionRatio (e.g. NodeImageProgram, NodeCircleProgram) do not display the issue. I'm unclear on where the difference is but this appears to be a significant difference between the programs that could explain this bug - I'm also under the impression that size calculation if nothing else is where the issue lies in the GLSL programs.

**Comment by jacomyal** [comment]
Thanks for the detailed report, it is very weird indeed. I have one more intuition though: It could be the hard limit on `WebGLRenderingContext.POINTS` programs, maybe. Does this issue occur with `WebGLRenderingContext.TRIANGLES` programs as well?

**Comment by gdotv** [comment]
Hey, that's a good point - after testing, I can confirm this is only occurring on .POINTS programs

**Comment by jacomyal** [comment]
OK, that is some good news: Basically, nodes drawn with the `POINTS` method cannot have a size larger than 100px. And since the sigma stage is often scaled to match the `devicePixelRatio`, on Retina displays, this limit can become 50 or sometimes even less I think.

Originally, the `node.point` program was used by default because it was way more efficient than `node.circle` in terms of memory. Now that we use instanced rendering, it is no longer true. Also, the new `@sigma/node-image` uses `TRIANGLES`, while the old `node.image` was based on the `POINTS` method.

We are discussing right now with @Yomguithereal about switching the default node program to `node.circle`. That could be a good solution.

**Comment by gdotv** [comment]
Thanks @jacomyal, that sounds great. Truly glad SigmaJS is run so expertly! I think incidentally the v2 NodeImageProgram had the same issue as it was using POINTS and so that's been fixed as part of the v3 move!

**Comment by jacomyal** [comment]
The latest beta version uses `NodeCircleProgram` as the default node renderer. I had to fix it a bit, because it was drawing nodes slightly larger than `NodePointProgram` does, but it's all good now.

I'm closing the issue now, as we can't do more on sigma's side. Thanks again for the report!

**Comment by gdotv** [comment]
Thanks @jacomyal, just a quick question, where does that leave the NodeBorderProgram? I know it's not part of the main suite of programs but it's definitely a useful one, I'm not sure if NodeCircleProgram offers border configurations.

**Comment by gdotv** [comment]
Makes sense, thanks!
------
Arthur Bigeard
Founder of gdotv
https://gdotv.com
