### ISSUE TITLE
Can't set Edge Size Smaller than 1 in 2.4.0

### ISSUE THREAD

**Issue by RaphaelHansen** [jacomyal/sigma.js#1428]
I've run into the same issue as the user [here:](https://stackoverflow.com/questions/70050882/smaller-edge-sizes-in-sigma-v2)

- Sigma.js version : 2.4.0 - Apologies if this has been fixed in later versions, please let me know. I'm not smart enough at the moment to upgrade without breaking everything.
- Graphology version : 0.23.0
- Operating system: Mac OSX 14.1.1 (23B81)
- Web browser: Chrome Latest
- **Steps to reproduce**
- Expected behavior:

As in Sigmajs version ~1.0 setting an edge size less than 1 creates an edge size less than one, this was done using the below in config.json:

`    "graphProperties": {
      "maxEdgeSize": 0.5,
      "minEdgeSize": 0.2,
      "minNodeSize": 1,
      "maxNodeSize": 7
`

- Actual behavior

Setting Edge size less than 1 does not reduce the edge size smaller than 1,

Tried setting it in graph.ForEachEdge:
`    graph.setEdgeAttribute(edge, "size", 0.1);`

Tried setting it in an edgeReducer:

`      edgeReducer: (edge, data) => {
        const defaultSize = 0.1;
        if (hoveredNode) {
          return graph.hasExtremity(edge, hoveredNode)
            ? { ...data, size: 0.1 }
            : { ...data, hidden: true };
        }
        if (isZooming){
          return{ ...data, hidden: true};
        }
        return { ...data, size: defaultSize};
      },
`

Both these code examples function and are able to change the edge size > 1 but less than one will always result in an edge size of 1. 

Apologies, I've been teaching myself all of this and am not the most technical person, thank you for any help.

**Comment by jacomyal** [comment]
In sigma v2+ (so it's still the same with the v3), there is only WebGL rendering, and the antialiasing is done by ourselves. We found a decent way to handle antialiasing, but it does not render properly too thin edges. So, there is an hardcoded limit inside the programs to ensure edges always have the minimal thickness to be rendered properly:

https://github.com/jacomyal/sigma.js/blob/459fe309eb061d3b50c960323c5ab4eebd67eaeb/packages/sigma/src/rendering/programs/edge-rectangle/vert.glsl.ts#L30-L32

For the record, here is what too thin edges at some zoom levels would look like without this minimal thickness limit:

![image](https://github.com/jacomyal/sigma.js/assets/144846/befb4c0f-14c0-45a1-b942-86d378779b90)

I'll keep this ticket opened so that we implement a way to overwrite this minimal edge thickness.

**Comment by jacomyal** [comment]
You can now override the [`minEdgeThickness` setting](https://github.com/jacomyal/sigma.js/blob/23e53736c9a95bd0bc81bdef9644be11e6d630c2/packages/sigma/src/settings.ts#L60) to get what you want..
