### ISSUE TITLE
Working ForceAtlas2 CDN hosted example that does not use npm/nodes or any server side rendering?

### ISSUE THREAD

**Issue by duaneking** [jacomyal/sigma.js#1470]
## Issue

The docs/demos are non-existent and stuff I find by googling assumes too much, or is actively misleading. Yet, if I look online, a lot of bugs have been filed because this has not been easily available to people. So providing this will also cut down on your support load.

I can find stuff for older versions, but they don't work in v2 and don't even seem compatible with the current quickstart:
-  https://jsfiddle.net/sim51/xck9a7yf/

I also really don't believe that the bot that's shutting peoples requests down is helping this project at all. And I would also like to, as a secondary goodwill gesture, ask that you look into that, because I do not believe that it is helping you based on the number of tickets it's closing that are not getting resolved.

**Is your feature request related to a problem? Please describe.**

This library desperately needs a working ForceAtlas2 example that does not use server side rendering, as that's simply not useful for most platforms using sigma.js via cdn, And I firmly believe that all of the focus on it being server side only is actively limiting this library and its usefulness for many people.

I'm not using node js at all, Just vanilla client side javascript development. Requiring that I use nodejs defeats the purpose of using javascript.

I'm not using react or any of its bloat due to legal restrictions (react is terrible for accessibility, node server side rendering is problematic for a number of legal and architectural reasons).

I have an interest in this library as a CDN hosted library that works only client side based on data presented by REST apis. I'm looking for a browser only example.

I don't want to use node at all, I just want to use a released package using a CDN and treat the browser as the client it is with a clean separation of concerns.

I was able to look at the quick start example and get started without ForceAtlas2 pretty quickly; But I'm now dealing with the fact that I absolutely do not want to manage X and Y in any way, shape or form by myself as my data set is very dynamic and I can't trust that these values can even be created accurately manually. It's also not a part of our data model at all. Googling says using ForceAtlas2 is my desired solution, But I literally cannot find a working example, anywhere.

**Describe the solution you'd like**
A working example of the ForceAtlas2 plug in that does not require server-side rendering and uses CDN files.

**Describe alternatives you've considered**
Removing this library from our product and warning people away from it.

**Additional context**

Looking at all the closed bugs, there have been a lot of people that have asked for things like this, but the stupid bot keeps closing them down before people can respond.

**Comment by duaneking** [comment]
#868

**Comment by duaneking** [comment]
#939

**Comment by jacomyal** [comment]
OK, here is how it works today:
- **Sigma** is a **rendering engine**, based on **graphology** (this is an information that appears very early, both in the README and the website).
- For anything interaction of rendering related, this GitHub repository is the best place to be.
- For anything data or graph-algorithm related (such as force-directed layouts, including ForceAtlas2, for instance), you can go to the related GitHub repository: https://github.com/graphology/graphology/issues
- For using the current version of **Sigma** without a **code bundler** (there is no "server-side rendering sigma.js", as sigma.js only works in a browser environment), the solution is indeed to import it from a CDN. Unfortunately, there is currently [an issue with CDN.js](https://github.com/cdnjs/cdnjs/issues/14261), that prevents the latest version of sigma to be available. There is a related sigma.js ticket [here](https://github.com/jacomyal/sigma.js/issues/1419).
- I have no idea how people can use [Graphology standard library](https://graphology.github.io/standard-library/) in a browser without a **code bundler**. You can apparently import [`graphology-library` from JSDeliver](https://github.com/graphology/graphology/issues/510), but I never tried it.

Finally, about this whole thing: I prefer to focus my limited resources on that free and open-source project for people who use a modern web-application stack, because we are designing and developing sigma.js more for **web applications** than for **web documents**. So I'm closing this issue.

Feel free to submit a working example for the documentation as a pull request, if you want to be helpful and if you think it could improve things for the community. Meanwhile, I'll spend some personal time on writing a Code of Conduct.

Have a good day.
