### ISSUE TITLE
retina display support

### ISSUE THREAD

**Issue by agayardo** [jacomyal/sigma.js#180]
The lines and text are blurry/pixelated when using a MacBook retina screen. 
The drawing code should take into account the devicePixelRatio as described here https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/HTML-canvas-guide/SettingUptheCanvas/SettingUptheCanvas.html and here http://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by mdamien** [comment]
Fixed in linkurious.js, do you want a PR ? https://github.com/Linkurious/linkurious.js/commit/e818f1a8693ce81efbad99444d6cd15795334cc9

Example:

* sigma.js : https://rawgit.com/jacomyal/sigma.js/master/examples/svg-renderer.html
* linkurious.js : https://rawgit.com/Linkurious/linkurious.js/develop/examples/svg-renderer.html

**Comment by Yomguithereal** [comment]
Hello @mdamien. I'll check your PR if you have time to file it. Thanks.
