### ISSUE TITLE
dispatch event click node event

### ISSUE THREAD

**Issue by renuy** [jacomyal/sigma.js#470]
Want to dispatch a click node event, when clicked from outside the graph(from a list of node labels). 
1. Is this supported
2. What all information needs to be dispatched (as part of fakeNode).
Trying it using the following code snippet

```
foundNode = sigma_obj.graph.nodes(node_id);
if (foundNode !== null) {
  // create fake data object
  var fakeData = {
    node: foundNode,
};
// dispatch event
sigma_obj.dispatchEvent('clickNode', fakeData);
```

Have binded(bound)  the clicknode event too, hence I know for sure, that the click node event is dispatched.
However, the label is not shown, which is shown when the node in the graph is actually clicked, that is the default clickNode behavior is not invoked.

Thanks
Renu

**Comment by deanshub** [comment]
i'm also waiting for this answer
:+1:

**Comment by jasontschool** [comment]
My understanding is that the label is shown on hover rather than click. I've looked at the source code for hovering and I know that label display is definitely shown there, though I can't say whether or not the same code is available in click.

Regardless, it sounds like you need to be dispatching the event to the renderer rather than the sigma object. I posted an example of triggering node hovers in https://github.com/jacomyal/sigma.js/issues/448 that might be adaptable for this purpose. Modifying the provided code:
```javascript
foundNode = sigma_obj.graph.nodes(node_id);
if (foundNode !== null) {
  // create fake data object
  var fakeData = {
    node: foundNode,
};
// dispatch event to renderer
// jasontschool: assuming there's only one renderer. If not, you'll need to have a reference to the right renderer (see the issue I linked)
sigma_obj.renderers[0].dispatchEvent('clickNode', fakeData);
 ```
