### ISSUE TITLE
How does the 'prefix' work in a canvas renderer?

### ISSUE THREAD

**Issue by louy2** [jacomyal/sigma.js#530]
I am writing a canvas node renderer which displays more information than `x`, `y`, and `size` from a node. So my node looks like:

```js
{
  x: 1,
  y: 1,
  size: 1,
  name: 'Physics',
  number: 101
}
```

And I want to display `number` inside the node, and `name` in the label.

I noticed in the `def` renderer `x` and `y` are not directly obtained but through a `prefix`. Regarding that the wiki states:

> With the Canvas renderer, to keep all these steps independants from each other, 
> every of these routines takes a prefix as input and sets the coordinates with a new 
> output. This makes possible to have multiple cameras running at the same time in 
> the same sigma instance.

In the same spirit I tried to obtain `number` in a similar fashion by `node[prefix + 'number']`, but it returned `undefined`. Direct access by `node.number` is working, but why is prefix not?

**Comment by 21stcaveman** [comment]
I second this, a little bit confused about the 'prefix' thing.

**Comment by louy2** [comment]
Now that I come back to it, the purpose of the prefix is to separate cameras, and in such case only `x` and `y`, namely the position, changes. All other properties should not change, otherwise the nodes displayed in different cameras will not be referring to the same node in the graph.

**Comment by Yomguithereal** [comment]
Hello @21stcaveman and @louy2, indeed the prefix only applies to the "geographical" properties of the node such as `x`, `y` and `size`. They are the mapping of your node's properties within different referentials such as the actually rendered position and the virtual camera position. This is made so because you might need them and so you can bind several cameras and/or renderers to a single graph.

**Comment by 21stcaveman** [comment]
@Yomguithereal , @louy2 Thank you, this clears things up!
