### ISSUE TITLE
Jagged nodes when setting minEdgeSize/maxEdgeSize

### ISSUE THREAD

**Issue by furukama** [jacomyal/sigma.js#634]
With the latest Chrome browser 45.0.2454.15, the nodes are not always round, but very jagged. The nodes only display as perfect circles when I remove the settings minEdgeSize and maxEdgeSize

Example:
![image](https://cloud.githubusercontent.com/assets/198717/9060036/2e61a15c-3ab0-11e5-9f8b-5cb333ef381d.png)
(URL: http://datalion.net/network/?id=unge)

With Firefox it works perfectly.

**Comment by AVermeij** [comment]
I had the exact same issue last week - seems to be specifically related to this version of Chrome, since all worked fine in other browsers and earlier Chrome versions. What fixed it for me was to disable hardware acceleration in Chrome's advanced settings.

Also see these links, seems to be a common issue:

https://code.google.com/p/chromium/issues/detail?id=469906
https://code.google.com/p/chromium/issues/detail?id=506625

**Comment by Yomguithereal** [comment]
Well this is quite a strange behavior indeed. Can you tell me whether further versions fix the problem so I can assess whether we should do something about it or let chrome fix this?

**Comment by AVermeij** [comment]
I haven't had this issue anymore since updating Chrome to the latest version, so I guess there are no fixes needed from your side :-)

**Comment by Yomguithereal** [comment]
Cool! Thanks anyway @AVermeij :).
