### ISSUE TITLE
Anyways to use ForceAtlas layout without using Sigma's rendering utilities?

### ISSUE THREAD

**Issue by nadirabid** [jacomyal/sigma.js#637]
Apologize in advance if this is where a question should be asked. @Yomguithereal Basically I wanted to test out the ForceAtlas2 layout but without having to render the graph through Sigma itself.

**Comment by RouxRC** [comment]
You should be able to do that by instantiating sigma with no renderer, this way every time FA2 calls sigma.refresh won't have anything to process for the visual rendering
Otherwise, you should probably fork the repo, comment the sigma.refresh line in FA2's code and build your own version of sigma with it.

**Comment by nadirabid** [comment]
I was able to get FA2 working without giving it a DOM element ID to bind to. Is there an explicit option to disable the renderer?

**Comment by RouxRC** [comment]
Looking at https://github.com/jacomyal/sigma.js/wiki/Public-API I guess instantiating sigma without a container is enough, otherwise maybe set renderers to an empty array but I guess that's what happens with no container

**Comment by nadirabid** [comment]
@RouxRC That works. Thanks for the help!
