### ISSUE TITLE
ConradId is not reset on killing a sigma instance / renderer

### ISSUE THREAD

**Issue by apitts** [jacomyal/sigma.js#713]
If you create an instance and then kill it and then create a new instance the prefix for a renderer will increment by 1 and keep incrementing. There seems to be some code when constructing a renderer that depends on conradId (which I can see is the scheduler library). Seems like it may make sense to reset conradId on killing a renderer?

**Comment by apitts** [comment]
Or more precisely sigma.utils.id()...perhaps we can reset that on killing an instance?

**Comment by Yomguithereal** [comment]
Hello @apitts. The goal of `sigma.utils.id` is to return a unique incremental id. Resetting it would be harmful since you can have several instances living on the same page and you would generate id collisions.

Are you having issues here when keeping renderers from one instance to the other when killing them? Is that it? If this is the case, you should probably kill your renderers and re-create them. I agree this is some kind of design issue but this would be a way to fix your problems.

**Comment by apitts** [comment]
Yeah - I was having an issue as the incremental id's cause havoc when trying to predict the prefix which is necessary I believe for layout algorithms that account for overlap (you have written previously on this). But I have worked out how to find the prefix of the current renderer now so it's OK. I still think it's a bit confusing to not decrement the id on killing renderers. Basically I kill the whole instance which also kills the renderers but the id's never decrement. Anyway, it's not causing any major issues for me now so closing the issue. Thanks!

**Comment by Yomguithereal** [comment]
> Yeah - I was having an issue as the incremental id's cause havoc when trying to predict the prefix which is necessary I believe for layout algorithms that account for overlap

The solution is merely to give an arbitrary id/name to your renderers/cameras.

**Comment by apitts** [comment]
Yeah, I thought that but haven't tried it yet as when I looked at the code it seemed to generate the id regardless of the id you give the renderer, i.e. the prefix id seemed separate from the actual id. But I could be wrong and will take another look.
