### ISSUE TITLE
noverlap plugin is stoping automatically within seconds after start

### ISSUE THREAD

**Issue by geekyminhaj** [jacomyal/sigma.js#835]
I am using noverlap plugin. I am starting it using **s.startNoverlap();** but when I test if this noverlap is running or not using **s.isNoverlapRunning();** then it is returning false. 
If I am correct it should return true as I have already started plugin.
I don't want to stop this noverlap plugin. How to keep this remain started ??
Any help will be greatly appreciated.
@apitts

**Comment by apitts** [comment]
@geekyminhaj The plugin is not in a webworker so I'm actually not sure how useful s.isNoverlapRunning() is since that function will probably only return post convergence in any case. It sounds like the algorithm is running and your nodes are still overlapping - is that the case? If so, the first place I would start would be with the settings. I would especially check the setting for the index of the renderer. I suggest you also review the noverlap example in the examples folder. If that is working for you then perhaps try to understand the differences between that example and your own code. You can also add some print statements into the noverlap algorithm to understand why you are seeing what you are seeing. Particularly around the collision calculation.

**Comment by geekyminhaj** [comment]
@apitts thanks for the details help. I will try the things you have mentioned.
Actually, I am working on one use case where I am using **noverlap** plugin along with **forceAtlas2**  plugin but nodes are still overlapping.
