### ISSUE TITLE
combine two graphs. older and newer versions of sigma. 

### ISSUE THREAD

**Issue by mudrak** [jacomyal/sigma.js#862]
Hi! 
I created a graph using Gephi and then exported it to sigma.js, using the plugin created by dr. Scott.
It includes the use of the geolocation plugin.
Here it is - https://mudrak.github.io/FECRFEOSA/#

However, I am trying to achieve something like this - https://mudrak.github.io/sigmasigma/
Could you please, recommend me the way to add nodes to the old version. I need the names to appear only after the country is clicked. Then, if the node is edged to the other one it gets displayed.

**Comment by Yomguithereal** [comment]
Unfortunately I never used the old version so I am a bit helpless here. @boogheta do you remember how?

**Comment by boogheta** [comment]
I don't really understand what's your objective exactly: do you want to hide nodes or labels? And is it to improve the first link or the second?
I don't know if there still exists somewhere some documentation for the old sigma, maybe @jacomyal knows...
Otherwise, you can find examples for the old sigma API looking at the code of your built interface from Oxford's gephi plugin here: https://mudrak.github.io/FECRFEOSA/js/main.js They handle hiding/showing on click already, so I guess you just need to adapt these pieces of code

**Comment by mudrak** [comment]
Thanks very much for the answer! 
Issue is solved. We wanted to hide nodes which were "names" in the json, unless the "country" node was clicked. https://mudrak.github.io/sigmasigma/ - the result.
