### ISSUE TITLE
Prevent Label overlap dynamically based on how far graph is zoomed out?

### ISSUE THREAD

**Issue by JohnSimerlink** [jacomyal/sigma.js#891]
![image](https://user-images.githubusercontent.com/4733612/29441904-5b2293ae-8383-11e7-8684-b32c14969c2d.png)

I want to make it so that labels don't overlap with eachother. Specifically I'd like to hide the overlapping labels. More specifically I'd like it so that if two nodes' labels' are overlapping, i could have my code choose (based on some calculation's on properties on the two nodes), which node's label to display.

What would be the best way of going about this?

**Comment by BrunoPFerreira** [comment]
> ![image](https://user-images.githubusercontent.com/4733612/29441904-5b2293ae-8383-11e7-8684-b32c14969c2d.png)
> 
> I want to make it so that labels don't overlap with eachother. Specifically I'd like to hide the overlapping labels. More specifically I'd like it so that if two nodes' labels' are overlapping, i could have my code choose (based on some calculation's on properties on the two nodes), which node's label to display.
> 
> What would be the best way of going about this?

Hi,
Did you manage to find a solution?
Thank you very much

**Comment by Yomguithereal** [comment]
@BrunoPFerreira this issue was related to v1 of sigma which is not maintained anymore. This should happen less in v2 thanks to grid optimization. But we cannot completely avoid collision because checking for those would be prohibitively costly to compute. But if you know the graph you want to display you can tweak [those](https://github.com/jacomyal/sigma.js/blob/main/src/settings.ts#L99-L101) settings to tailor the label display to your graph.
