### ISSUE TITLE
Change cursor to hand when hovering on clickable node

### ISSUE THREAD

**Issue by ZhaofengWu** [jacomyal/sigma.js#898]
Is there any way to do that?

**Comment by AVermeij** [comment]
Assuming `s` is your sigma instance and `sigma-container` is the container holding your sigma canvas, you can use the following to achieve this:

```
// Set cursor to pointer (hand) when hovering over a node
s.bind('overNode', function(e) {
  document.getElementById('sigma-container').style.cursor = 'pointer';
});

// Make sure to revert to default cursor again when moving out of nodes
s.bind('outNode', function(e) {
  document.getElementById('sigma-container').style.cursor = 'default';
});

**Comment by wthrajat** [comment]
This did not work for me for some reason. I found a new approach to this and this works like a charm for me. For anyone on the same boots as me, I recommend trying this approach:
```
    s.on("enterNode", ({ node }) => {
      setHoveredNode(node);
      container.style.cursor = "pointer";
    });
    s.on("leaveNode", () => {
      setHoveredNode(undefined);
      container.style.cursor = "default";
    });
```
This keeps in mind that `s` is the sigma instance like the above example.
(I think @ZhaofengWu's approach didn't work for me because Sigma was throwing an error that `s.bind` isn't a function.
