### ISSUE TITLE
Forceatlas settings and sparsity 

### ISSUE THREAD

**Issue by CptCurty** [jacomyal/sigma.js#961]
It seems as it the settings for forceAtlas don't work so well. For some reason nodes keep bouncing around while the graph should be completely still. I'm not sure if this is a problem with the settings, but I was unable to prevent the bouncing, only delay it with a large slowDown. Furthermore, the option scalingRatio seems to do nothing at all for my large graph. Do anybody know how to make a graph with a lot of nodes wider and more sparse? With d3 you are able to define a minimum distance between nodes, but I assume this is not possible with sigma?

**Comment by Yomguithereal** [comment]
What’s the scale of your graph. FA was designed to work with large number of nodes.

**Comment by Yomguithereal** [comment]
I mean that with fairly tiny graphs (~< 50 nodes), FA tends to jitter a lot because it does not aim at handling those cases very well.

**Comment by AVermeij** [comment]
It also tends to jitter more when you're using ``barnesHutOptimize``, because of the use of a quadtree. 

About the scaling, ``scalingRatio`` actually works as expected, it's just that sigma's ``autoRescale`` middleware (which defaults to ``true``) kind of diminishes its effect.

Try setting the ``autoRescale`` setting to ``['nodeSize']`` and you'll probably see what I mean :-)

**Comment by CptCurty** [comment]
I'll check it out. Thanks!

**Comment by CptCurty** [comment]
it works now! Thanks!
